# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Simple sales pop"
client_id = "245a105223c9ed3d0cde809d791aab60"
application_url = "https://olympics-essays-lindsay-operators.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://olympics-essays-lindsay-operators.trycloudflare.com/auth/shopify/callback",
  "https://olympics-essays-lindsay-operators.trycloudflare.com/authSa/shopify/callback",
  "https://olympics-essays-lindsay-operators.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nam-devstore.myshopify.com"
